<a href="https://colab.research.google.com/github/rigole/TensorFlow-Learning/blob/main/TensorLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constants


In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.5.0'

In [4]:
# Defining a tensorflow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

# Variables


In [6]:
# Defining a variable in TensorFlow
variable = tf.Variable([[30, 20],[10, 45]])

In [7]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

# Building Artificial Neural Network

### Importing the librairies and the data set

In [8]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

### Loading the data set

In [9]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


### Normalizing the images

In [10]:
X_train = X_train / 255.0

In [11]:
X_test = X_test / 255.0

### Reshaping the dataset
##### since each image's dimension is 28x28, we reshape the full dataset to [-1, height * width]

In [12]:
X_train = X_train.reshape(-1, 28*28)

In [13]:
X_train.shape

(60000, 784)

In [14]:
# same for the the test shape
X_test = X_test.reshape(-1, 28*28)

### Defining the model

In [15]:
#simply define an object of the Sequential model
model = tf.keras.models.Sequential()

### Adding a first fully connected hidden layer

In [16]:
#layers parameters
  #numbers of units/neurons(128), action_function(ReLU), input_shape(784,)

model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

### Adding a Second Layer 

In [17]:
model.add(tf.keras.layers.Dropout(0.2))

### Adding the output layer

In [18]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

### Compiling the model

In [19]:
 model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


### Training the model

In [21]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.5320 - sparse_categorical_accuracy: 0.8111
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3990 - sparse_categorical_accuracy: 0.8561
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3657 - sparse_categorical_accuracy: 0.8674
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3475 - sparse_categorical_accuracy: 0.8737
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3306 - sparse_categorical_accuracy: 0.8795


## Model evaluation and prediction

In [22]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.3614 - sparse_categorical_accuracy: 0.8680


# Convolutional Neural Networks

### Importing the librairies

In [25]:
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.datasets import cifar10
%matplotlib inline

### Data Preprocessing

#### loading the cirfar10 dataset

In [26]:
# Setting class names in the dataset
class_names = ['airplane', 'automobile', 'bird','cat', 'dog','frog','horse','ship','truck']