<a href="https://colab.research.google.com/github/rigole/TensorFlow-Learning/blob/main/TensorLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constants


In [1]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [3]:
# Defining a tensorflow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

# Variables


In [ ]:
# Defining a variable in TensorFlow
variable = tf.Variable([[30, 20],[10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

# Building Artificial Neural Network

### Importing the librairies and the data set

In [4]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

### Loading the data set

In [22]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

### Normalizing the images

In [9]:
X_train = X_train / 255.0

In [10]:
X_test = X_test / 255.0

### Reshaping the dataset
##### since each image's dimension is 28x28, we reshape the full dataset to [-1, height * width]

In [12]:
X_train = X_train.reshape(-1, 28*28)

In [14]:
X_train.shape

(60000, 784)

In [15]:
# same for the the test shape
X_test = X_test.reshape(-1, 28*28)

### Defining the model

In [18]:
#simply define an object of the Sequential model
model = tf.keras.models.Sequential()

### Adding a first fully connected hidden layer

In [17]:
#layers parameters
  #numbers of units/neurons(128), action_function(ReLU), input_shape(784,)

model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

### Adding a Second Layer 

In [19]:
model.add(tf.keras.layers.Dropout(0.2))

### Adding the output layer

In [21]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))