<a href="https://colab.research.google.com/github/rigole/TensorFlow-Learning/blob/main/TensorLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constants


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [ ]:
# Defining a tensorflow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

# Variables


In [ ]:
# Defining a variable in TensorFlow
variable = tf.Variable([[30, 20],[10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

# Building Artificial Neural Network

In [1]:
# Importing the librairies and the data set

import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [3]:
# Loading the data set
(X_train, y_train),(X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


we divide each of the image in the training and test set by the minimum number of pixels(255).

In this way each pixel will be in the range [0,1]. By normalizing images we make sure that our model train faster

In [4]:
 # Normalizing the images

X_train = X_train / 255.0

In [5]:
X_test = X_test / 255.0

Since we are building a fully connected network, we reshape the training set and the test set to be into the vector format

In [6]:
# Reshaping the dataset
## since each image's dimension is 28x28, we reshape the full dataset to [-1, height * width]

X_train = X_train.reshape(-1, 28*28)

In [7]:
X_train.shape

(60000, 784)

In [8]:
# same for the the test shape
X_test = X_test.reshape(-1, 28*28)

Building the Artificial Neural Network

In [9]:
# Defining the model
#simply define an object of the Sequential model

model = tf.keras.models.Sequential()