<a href="https://colab.research.google.com/github/rigole/TensorFlow-Learning/blob/main/TensorLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constants


In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
# Defining a tensorflow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

# Variables


In [5]:
# Defining a variable in TensorFlow
variable = tf.Variable([[30, 20],[10, 45]])

In [6]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

# Building Artificial Neural Network

### Importing the librairies and the data set

In [7]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

### Loading the data set

In [8]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


### Normalizing the images

In [9]:
X_train = X_train / 255.0

In [10]:
X_test = X_test / 255.0

### Reshaping the dataset
##### since each image's dimension is 28x28, we reshape the full dataset to [-1, height * width]

In [11]:
X_train = X_train.reshape(-1, 28*28)

In [12]:
X_train.shape

(60000, 784)

In [13]:
# same for the the test shape
X_test = X_test.reshape(-1, 28*28)

### Defining the model

In [14]:
#simply define an object of the Sequential model
model = tf.keras.models.Sequential()

### Adding a first fully connected hidden layer

In [15]:
#layers parameters
  #numbers of units/neurons(128), action_function(ReLU), input_shape(784,)

model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

### Adding a Second Layer 

In [16]:
model.add(tf.keras.layers.Dropout(0.2))

### Adding the output layer

In [17]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

### Compiling the model

In [18]:
 model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
