<a href="https://colab.research.google.com/github/rigole/TensorFlow-Learning/blob/main/TensorLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constants


In [1]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.5.0'

In [3]:
# Defining a tensorflow constant
tensor = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

# Variables


In [ ]:
# Defining a variable in TensorFlow
variable = tf.Variable([[30, 20],[10, 45]])

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

# Building Artificial Neural Network

In [4]:
# Importing the librairies and the data set

import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [8]:
# Loading the data set
(X_train, y_train),(X_test, y_test) = fashion_mnist.load_data()

we divide each of the image in the training and test set by the minimum number of pixels(255).

In this way each pixel will be in the range [0,1]. By normalizing images we make sure that our model train faster

In [9]:
 # Normalizing the images

X_train = X_train / 255.0

In [10]:
X_test = X_test / 255.0

Since we are building a fully connected network, we reshape the training set and the test set to be into the vector format

In [12]:
# Reshaping the dataset
## since each image's dimension is 28x28, we reshape the full dataset to [-1, height * width]

X_train = X_train.reshape(-1, 28*28)

In [14]:
X_train.shape

(60000, 784)

In [15]:
# same for the the test shape
X_test = X_test.reshape(-1, 28*28)

Building the Artificial Neural Network

In [18]:
# Defining the model
#simply define an object of the Sequential model

model = tf.keras.models.Sequential()

In [17]:
# Adding a first fully connected hidden layer
 #layers parameters
  #numbers of units/neurons(128), action_function(ReLU), input_shape(784,)

model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

In [19]:
# Adding a Second Layer 
model.add(tf.keras.layers.Dropout(0.2))

In [21]:
# Adding the output layer
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))